### ISSUE TITLE
Response::bytes throws `Error: expected a number argument`

### ISSUE THREAD

**Issue by platy** [seed-rs/seed#427]
Calling the `bytes()` function on the response of a fetch call, ie.
```rust
fetch(url).await.unwrap().bytes().await;
```
Causes the following error:
```
Stack:
Error: expected a number argument
    at _assertNum (http://localhost:8000/pkg/package.js:224:39)
    at imports.wbg.__wbg_length_b7dc6aed3ca09be1 (http://localhost:8000/pkg/package.js:1565:13)
    at js_sys::Uint8Array::length::h25f34bf3ef34d05a (wasm-function[3874]:0x17bcdf)
    at js_sys::Uint8Array::to_vec::hdf9eb12ced7141ca (wasm-function[1982]:0x13cfe3)
    at seed::browser::fetch::response::Response::bytes::{{closure}}::h188a81966303f00c (wasm-function[211]:0x6c06c)
```

I set a breakpoint and found that the `js_sys::Uint8Array` is actually wrapping an `ArrayBuffer`.
I believe the issue is that `Response::bytes` is calling `Uint8Array::from` instead of `Uint8Array::new` and it looks like js_sys then has an `ArrayBuffer` which it thinks is a `Uint8Array`. I'll make a PR and add a test.

**Comment by MartinKavik** [comment]
PR and test very welcome. 
I've written this feature too fast because one user on the chat needed it and I hoped he will test it in a reasonable time and I'll add tests after that. However it freezed somewhere.
Thank you!
